version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "10000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: city-break-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - "10001:8080"
    depends_on:
      - mysql
